/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PassportBatchIdRouteImport } from './routes/passport.$batchId'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DashboardCreateBatchRouteImport } from './routes/dashboard.create-batch'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PassportBatchIdRoute = PassportBatchIdRouteImport.update({
  id: '/passport/$batchId',
  path: '/passport/$batchId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCreateBatchRoute = DashboardCreateBatchRouteImport.update({
  id: '/dashboard/create-batch',
  path: '/create-batch',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/passport/$batchId': typeof PassportBatchIdRoute
  '/dashboard': typeof DashboardRoute
  '/dashboard/create-batch': typeof DashboardCreateBatchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/passport/$batchId': typeof PassportBatchIdRoute
  '/dashboard': typeof DashboardRoute
  '/dashboard/create-batch': typeof DashboardCreateBatchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/passport/$batchId': typeof PassportBatchIdRoute
  '/dashboard': typeof DashboardRoute
  '/dashboard/create-batch': typeof DashboardCreateBatchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/passport/$batchId' | '/dashboard' | '/dashboard/create-batch'
  fileRoutesByTo: FileRoutesByTo
  fileRoutesById: FileRoutesById
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passport/$batchId': {
      id: '/passport/$batchId'
      path: '/passport/$batchId'
      fullPath: '/passport/$batchId'
      preLoaderRoute: typeof PassportBatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/create-batch': {
      id: '/dashboard/create-batch'
      path: '/create-batch'
      fullPath: '/dashboard/create-batch'
      preLoaderRoute: typeof DashboardCreateBatchRouteImport
      parentRoute: typeof DashboardRouteImport
    }
  }
}

const dashboardRouteChildren = {
  DashboardCreateBatchRoute: DashboardCreateBatchRoute,
}

const rootRouteChildren = {
  IndexRoute: IndexRoute,
  PassportBatchIdRoute: PassportBatchIdRoute,
  DashboardRoute: DashboardRoute._addFileChildren(dashboardRouteChildren),
}

export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
